### PR TITLE
Ctrl c dont exits

### PR DESCRIPTION
**Pull request by ramn**
As discussed in https://github.com/DavidGriffith/frotz/issues/11

### CODE REVIEW

**Comment by dchapes** [comment]
Please don't change my Ctrl+C behaviour.

**Comment by ramn** [comment]
@dchapes that is not true - try hitting ctrl-c in vim or emacs for example. It won't terminate the application. Neither should it terminate frotz.

**Comment by DavidGriffith** [comment]
For some reason Frotz uses cbreak() mode.  Right next to that call are comments that we're doing raw input mode.  It was like that since 2.32r2.  I think it would be better to use raw mode and go from there.

**Comment by DavidGriffith** [comment]
I'd rather not stop Ctrl-C from exiting Frotz by messing with signal processing.  See #37.  I plan to dig around in the curses documentation to make Frotz work in raw mode.  I'm not sure why @StefanJokisch chose to use cbreak mode.

**Pull request closed without merging**
